"""Automated migration

Revision ID: d3a978620be4
Revises: 
Create Date: 2025-03-06 19:33:12.746701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a978620be4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professeur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('specialite', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professeur_cours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professeur_id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professeur_cours')
    op.drop_table('professeur')
    # ### end Alembic commands ###
