apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-classes
spec:
  replicas: {{ .Values.replicas.classes }}
  selector:
    matchLabels:
      app: microservice-classes
  template:
    metadata:
      labels:
        app: microservice-classes
    spec:
      containers:
        - name: microservice-classes
          image: "{{ .Values.image.classes }}"  # Récupère l'image depuis values.yaml
          ports:
            - containerPort: 5001
          env:
            - name: DATABASE_URL
              value: "{{ .Values.database.classes }}"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-classes
spec:
  selector:
    app: microservice-classes
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
