apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: {{ .Values.replicas.grafana | default 1 }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: {{ .Values.image.grafana | default "grafana/grafana:latest" }}
        ports:
        - containerPort: 3000  # Grafana écoute toujours sur 3000 en interne
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: {{ .Values.grafana.adminPassword | default "admin" }}  
        resources:
          requests:
            memory: {{ .Values.grafana.resources.requests.memory | default "500Mi" }}
            cpu: {{ .Values.grafana.resources.requests.cpu | default "500m" }}
          limits:
            memory: {{ .Values.grafana.resources.limits.memory | default "1Gi" }}
            cpu: {{ .Values.grafana.resources.limits.cpu | default "1" }}
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 4000      # Port externe exposé
      targetPort: 3000 # Port interne du conteneur Grafana
      nodePort: 32000  # Si type NodePort est utilisé
  type: {{ .Values.service.type | default "LoadBalancer" }}
