apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: {{ .Values.replicas.loki | default 1 }}
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: {{ .Values.image.loki | default "grafana/loki:latest" }}
          args:
            - "-config.file=/etc/loki/loki-config.yaml"
          resources:
            requests:
              cpu: {{ .Values.loki.resources.requests.cpu | default "100m" }}
              memory: {{ .Values.loki.resources.requests.memory | default "128Mi" }}
            limits:
              cpu: {{ .Values.loki.resources.limits.cpu | default "500m" }}
              memory: {{ .Values.loki.resources.limits.memory | default "512Mi" }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/loki
            - name: data
              mountPath: /var/loki
      volumes:
        - name: config-volume
          configMap:
            name: loki-config
        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  type: {{ .Values.service.type | default "LoadBalancer" }}
