apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-postgres-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storage | default '1Gi' }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-postgres"
spec:
  replicas: {{ .Values.replicas.postgres | default 1 }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.postgres | default 'postgres:latest' }}"
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.env.POSTGRES_USER | default 'postgres' }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.env.POSTGRES_PASSWORD | default 'Redington' }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.env.POSTGRES_DB | default 'school_db' }}
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: {{ .Values.postgres.resources.requests.cpu | default '250m' }}
              memory: {{ .Values.postgres.resources.requests.memory | default '512Mi' }}
            limits:
              cpu: {{ .Values.postgres.resources.limits.cpu | default '1' }}
              memory: {{ .Values.postgres.resources.limits.memory | default '1Gi' }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-postgres-pvc"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-postgres"
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
