apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: {{ .Values.replicas.prometheus | default 1 }}
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.image.prometheus | default "prom/prometheus:latest" }}
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
              subPath: prometheus.yml
          resources:
            requests:
              memory: {{ .Values.prometheus.resources.requests.memory | default "500Mi" }}
              cpu: {{ .Values.prometheus.resources.requests.cpu | default "500m" }}
            limits:
              memory: {{ .Values.prometheus.resources.limits.memory | default "1Gi" }}
              cpu: {{ .Values.prometheus.resources.limits.cpu | default "1" }}
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  clusterIP: None
  type: {{ .Values.service.type | default "LoadBalancer" }}
