apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: monitoring
spec:
  replicas: {{ .Values.replicas.promtail | default 1 }}
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: {{ .Values.image.promtail | default "grafana/promtail:latest" }}
          args:
            - "-config.file=/etc/promtail/promtail-config.yaml"
          resources:
            requests:
              cpu: {{ .Values.promtail.resources.requests.cpu | default "100m" }}
              memory: {{ .Values.promtail.resources.requests.memory | default "128Mi" }}
            limits:
              cpu: {{ .Values.promtail.resources.limits.cpu | default "500m" }}
              memory: {{ .Values.promtail.resources.limits.memory | default "512Mi" }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/promtail
            - name: logs
              mountPath: /var/log
      volumes:
        - name: config-volume
          configMap:
            name: promtail-config
        - name: logs
          hostPath:
            path: /var/log
